import { Modal } from 'antd'

type AgreementModalProps = {
  isOpen: boolean
  setIsOpen: () => void
}

function AgreementModal ({ isOpen, setIsOpen }: AgreementModalProps): JSX.Element {
  return (
        <Modal
            open={isOpen}
            onCancel={setIsOpen}
            title="Agreement"
            footer={null}
        >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vel elit scelerisque mauris pellentesque pulvinar pellentesque. Neque vitae tempus quam pellentesque nec. Ultrices mi tempus imperdiet nulla. Sagittis orci a scelerisque purus semper. Interdum consectetur libero id faucibus nisl tincidunt. Leo integer malesuada nunc vel risus commodo viverra maecenas. Arcu cursus vitae congue mauris rhoncus aenean. Sit amet consectetur adipiscing elit ut. Blandit cursus risus at ultrices mi tempus imperdiet nulla. Diam ut venenatis tellus in metus. Proin fermentum leo vel orci porta. Massa sed elementum tempus egestas sed sed. Nunc sed id semper risus in hendrerit gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. Id aliquet risus feugiat in ante metus dictum at tempor. Cursus vitae congue mauris rhoncus.
            Blandit massa enim nec dui nunc mattis. Arcu felis bibendum ut tristique et egestas. Sagittis purus sit amet volutpat consequat mauris. Donec enim diam vulputate ut pharetra sit. Pellentesque massa placerat duis ultricies lacus sed turpis. Vel turpis nunc eget lorem dolor. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc. Auctor neque vitae tempus quam pellentesque nec nam. Maecenas pharetra convallis posuere morbi leo urna molestie at elementum. Vel eros donec ac odio tempor orci dapibus. Ultricies mi eget mauris pharetra et ultrices neque ornare. Nam libero justo laoreet sit amet cursus. Laoreet suspendisse interdum consectetur libero. Ipsum consequat nisl vel pretium lectus quam id leo. Malesuada bibendum arcu vitae elementum curabitur vitae. Cursus in hac habitasse platea dictumst quisque. Ipsum nunc aliquet bibendum enim facilisis gravida neque convallis. Lorem dolor sed viverra ipsum.
            Lorem dolor sed viverra ipsum nunc aliquet bibendum enim. Non curabitur gravida arcu ac tortor dignissim convallis aenean. Lorem ipsum dolor sit amet. Ut porttitor leo a diam sollicitudin tempor id eu. Risus in hendrerit gravida rutrum quisque non tellus orci. Ornare aenean euismod elementum nisi. Leo a diam sollicitudin tempor id eu. Nulla porttitor massa id neque aliquam vestibulum morbi blandit cursus. Diam quam nulla porttitor massa id. Luctus accumsan tortor posuere ac. Diam maecenas sed enim ut. Enim sit amet venenatis urna cursus eget. Posuere urna nec tincidunt praesent. Ut tristique et egestas quis ipsum suspendisse ultrices gravida dictum. Fermentum dui faucibus in ornare quam viverra orci. Facilisis magna etiam tempor orci eu lobortis. Amet dictum sit amet justo donec. Elementum nisi quis eleifend quam adipiscing vitae. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim. Enim ut tellus elementum sagittis vitae et.
            Sed viverra tellus in hac. Sit amet purus gravida quis blandit turpis cursus. Metus aliquam eleifend mi in. Augue interdum velit euismod in pellentesque massa. Vestibulum lectus mauris ultrices eros in. A pellentesque sit amet porttitor eget dolor morbi non arcu. Convallis aenean et tortor at risus viverra adipiscing at. Mattis aliquam faucibus purus in massa tempor. Ipsum dolor sit amet consectetur adipiscing elit. Ut placerat orci nulla pellentesque dignissim enim sit. Magna fringilla urna porttitor rhoncus dolor purus non enim praesent. Etiam dignissim diam quis enim lobortis scelerisque fermentum.
            Gravida neque convallis a cras semper auctor. Eget velit aliquet sagittis id consectetur. Faucibus in ornare quam viverra orci. Augue mauris augue neque gravida in. Quis varius quam quisque id. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. In nulla posuere sollicitudin aliquam. Ultrices tincidunt arcu non sodales neque. Vel facilisis volutpat est velit egestas dui id ornare. Varius quam quisque id diam vel quam elementum. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna. Etiam tempor orci eu lobortis elementum nibh tellus. At lectus urna duis convallis convallis tellus id interdum. Sit amet mattis vulputate enim nulla aliquet. Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant. Sem nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Enim ut sem viverra aliquet. Eget felis eget nunc lobortis mattis.
            Et tortor consequat id porta nibh venenatis cras sed. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Pharetra sit amet aliquam id diam. Augue interdum velit euismod in pellentesque massa placerat duis. Fermentum leo vel orci porta non pulvinar neque laoreet. Eget nulla facilisi etiam dignissim. Purus in mollis nunc sed. Porttitor massa id neque aliquam vestibulum. Eu lobortis elementum nibh tellus molestie. Semper quis lectus nulla at volutpat diam ut. Sit amet luctus venenatis lectus magna. Velit scelerisque in dictum non consectetur a erat nam. In tellus integer feugiat scelerisque varius morbi. Eu sem integer vitae justo eget magna. Gravida neque convallis a cras semper auctor. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Ut pharetra sit amet aliquam id diam.
            Facilisis magna etiam tempor orci. Orci ac auctor augue mauris. Eget velit aliquet sagittis id consectetur purus ut faucibus. Est velit egestas dui id. Neque laoreet suspendisse interdum consectetur libero id. Volutpat blandit aliquam etiam erat velit scelerisque in. Risus commodo viverra maecenas accumsan lacus vel. Viverra suspendisse potenti nullam ac tortor vitae purus. Cras adipiscing enim eu turpis egestas pretium. Mus mauris vitae ultricies leo integer malesuada. Eget felis eget nunc lobortis mattis. Augue neque gravida in fermentum et. Quam id leo in vitae. Elit ut aliquam purus sit amet. Rhoncus dolor purus non enim praesent elementum facilisis leo vel.
            Parturient montes nascetur ridiculus mus mauris vitae. Purus in massa tempor nec feugiat nisl pretium fusce. Cursus risus at ultrices mi tempus imperdiet nulla malesuada. Metus aliquam eleifend mi in nulla posuere sollicitudin. Dui nunc mattis enim ut tellus elementum sagittis vitae et. Risus quis varius quam quisque id diam. Lobortis mattis aliquam faucibus purus in massa tempor nec feugiat. Vel quam elementum pulvinar etiam non quam. Bibendum enim facilisis gravida neque convallis a cras. Tempus urna et pharetra pharetra massa. Euismod nisi porta lorem mollis aliquam. Enim lobortis scelerisque fermentum dui faucibus. Diam sollicitudin tempor id eu nisl.
            Integer malesuada nunc vel risus commodo viverra maecenas accumsan. Sapien eget mi proin sed libero enim sed. Pretium lectus quam id leo in vitae turpis. Vivamus at augue eget arcu dictum varius duis at consectetur. Aliquet lectus proin nibh nisl condimentum. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra accumsan. Sed egestas egestas fringilla phasellus. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula ipsum. Ornare massa eget egestas purus viverra accumsan in nisl. Id aliquet lectus proin nibh nisl. In metus vulputate eu scelerisque. Mollis nunc sed id semper. In nibh mauris cursus mattis molestie a iaculis.
            Eget mi proin sed libero. Ultricies leo integer malesuada nunc vel risus. Cursus sit amet dictum sit amet justo donec. Et netus et malesuada fames ac turpis egestas integer eget. Volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque in. Mus mauris vitae ultricies leo integer malesuada nunc vel risus. Sapien pellentesque habitant morbi tristique senectus et netus et malesuada. Arcu non odio euismod lacinia at quis risus sed vulputate. Consectetur adipiscing elit duis tristique sollicitudin nibh sit. Est lorem ipsum dolor sit amet.
        </Modal>
  )
}

export default AgreementModal
