name: Linter/Build/Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install
      run: npm i

    - name: Lint test
      run: npm run lint

    - name: Build
      run: npm run build
      env:
        VITE_SERVER_BASE_URL: ${{ secrets.VITE_SERVER_BASE_URL }}
        VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}

    - name: Deploy
      uses: garygrossgarten/github-action-scp@release
      with:
        local: dist
        remote: /usr/share/nginx/html
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
